# Generated by Django 4.0.4 on 2022-04-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=250)),
                ('cif', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentrio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('finalizada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('albaran', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cabSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cabsalida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombreComercial', models.CharField(max_length=100)),
                ('noregistro', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('plazoSeguridad', models.IntegerField()),
                ('tipoTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.tipotratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.conceptogasto')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cultivo')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=250)),
                ('campanya', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cliente')),
            ],
        ),
    ]
