# Generated by Django 4.0.4 on 2022-05-07 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('domicilio', models.CharField(default='', max_length=250)),
                ('cif', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(default=' ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('nombreComercial', models.CharField(default='', max_length=100)),
                ('noregistro', models.CharField(default='', max_length=100)),
                ('precio', models.FloatField(default=0)),
                ('plazoSeguridad', models.IntegerField(default=0)),
                ('noDisponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('precio', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('finalizada', models.IntegerField(default=0)),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controlfitos.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='VariedadesTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.tratamiento')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('albaran', models.CharField(default='', max_length=100)),
                ('factura', models.CharField(default='', max_length=100)),
                ('cabSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cabsalida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cliente')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.variedad')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoTratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.tipotratamiento'),
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('campanya', models.CharField(default='', max_length=100)),
                ('domicilio', models.CharField(default='', max_length=250)),
                ('cif', models.CharField(default='', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cliente')),
            ],
        ),
    ]
