# Generated by Django 4.0.4 on 2022-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptogasto',
            name='comentario',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
