# Generated by Django 4.0.4 on 2022-05-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0002_alter_variedad_cultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedad',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.cultivo'),
        ),
    ]
