# Generated by Django 4.0.4 on 2022-04-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0002_alter_conceptogasto_comentario'),
    ]

    operations = [
    ]
