# Generated by Django 4.0.4 on 2022-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0003_auto_20220424_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedadestratamiento',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
