# Generated by Django 4.0.4 on 2022-05-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0004_remove_variedadestratamiento_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
