# Generated by Django 4.0.4 on 2022-04-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0004_variedadestratamiento_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariedadesTratamiento',
        ),
    ]
