# Generated by Django 4.0.4 on 2022-04-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0005_delete_variedadestratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariedadesTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.tratamiento')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.variedad')),
            ],
        ),
    ]
