# Generated by Django 4.0.4 on 2022-04-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0006_variedadestratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cif',
        ),
    ]
