# Generated by Django 4.0.4 on 2022-04-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0008_cliente_cif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='variedad',
        ),
    ]
