# Generated by Django 4.0.4 on 2022-04-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0009_remove_salida_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='variedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='controlfitos.variedad'),
            preserve_default=False,
        ),
    ]
