# Generated by Django 4.0.4 on 2022-04-29 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0010_salida_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 4, 30)),
        ),
    ]
