# Generated by Django 4.0.4 on 2022-05-01 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0011_salida_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='producto',
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
    ]
