# Generated by Django 4.0.4 on 2022-05-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlfitos', '0012_remove_tratamiento_producto_alter_salida_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfitos.producto'),
            preserve_default=False,
        ),
    ]
